MACHINES = {
  :consul => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.100'
  },
  :app => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.50'
  },
  :pg0 => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.120'
  },
  :pg1 => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.121'
  },
  :pg2 => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.122'
  },
  :haproxy => {
        :box_name => "ubuntu/bionic64",
        :ip_addr => '192.168.11.101'
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "512"]
          end
      end
  end
end
