version: "3.5"
services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER:     "otusdb"
      POSTGRES_PASSWORD: "otusdb"
      POSTGRES_DB:       "otusdb"
    networks:
      - otusdb-nw
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "otusdb"]
      interval: 10s
      timeout: 5s
      retries: 60

networks:
  otusdb-nw:
    name: otusdb-network
